# JDBC URL
spring.datasource.url={$messaging_app_database_url}
# DB credentials
spring.datasource.username={$messaging_app_database_username}
spring.datasource.password={$messaging_app_database_password}

# HikariCP settings (connection pool)

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000  
spring.datasource.hikari.max-lifetime=1800000 

server.address=0.0.0.0
server.port=8080

jwt.secret=${JWT_SECRET}
